### ISSUE TITLE
Addon prevents robots.txt from being returned

### ISSUE THREAD

**Issue by kiwi-josh** [DockYard/ember-service-worker-index#1]
## Version
Version 0.6.1

## Steps to reproduce
Install these addons:
```
ember install ember-service-worker
ember install ember-service-worker-index
ember install ember-service-worker-asset-cache
ember install ember-service-worker-cache-fallback
```

## Expected Behavior
Navigate to my-website.com/robots.txt -> robots.txt file served.

## Actual Behavior
Navigate to my-website.com/robots.txt -> ember-service-worker-index intercepts request and returns workers cached index.html file.

**Comment by bcardarella** [comment]
this shouldn't be the case with crawlers

**Comment by broerse** [comment]
Confirmed it returns index.html:

https://bloggr.exmer.com/robots.txt

But is also happens for:

https://bloggr.exmer.com/favicon.ico
https://bloggr.exmer.com/browserconfig.xml
https://bloggr.exmer.com/safari-pinned-tab.svg
https://bloggr.exmer.com/android-chrome-512x512.png
etc.

@bcardarella Crawlers can from Chrome version 60 use headless Chrome ;-)

**Comment by bcardarella** [comment]
The file is there, but in your browser the SW loads up. If you do a hard refresh (CMD-SHIFT-R) you'll see the files.

This is because the SW is a bit too aggressive with what it matches on. I think we may be able to use the router to export the routes to match against but I'd have to look into this a bit more to see if it makes sense.

**Comment by bcardarella** [comment]
> Crawlers can from Chrome version 60 use headless Chrome ;-)

I believe that crawlers using Chrome in headless mode should be turning off cookies which would disable service workers.

**Comment by broerse** [comment]
CouchDB needs a rewrites file for this created from distFiles. Perhaps if the router is to hard to interpret we can do something similar upfront. See:

https://github.com/martinic/ember-cli-deploy-couchdb/blob/master/index.js#L68

**Comment by jrjohnson** [comment]
This also intercepts and breaks:
* URLs on the server that have nothing to do with ember like `/Shibboleth.SSO`
