### ISSUE TITLE
Need the latest code published to NPM

### ISSUE THREAD

**Issue by stephencweiss** [DockYard/ember-service-worker-index#20]
In https://github.com/DockYard/ember-service-worker-index/pull/18 we updated the code, but haven't yet published a new version to the registry meaning it's not publicly available.

It would be lovely if we could get this pushed out so we can all benefit from it :) 

Thanks!

**Comment by stephencweiss** [comment]
@marten-dockyard -- any chance I can get 👀  on this?

**Comment by stephencweiss** [comment]
@eshtadc - pinging you in case you still have access (looks like you're on the NPM package). Thanks!

**Comment by duggiefresh** [comment]
@stephencweiss Hello! 👋 Apologies for the long wait on a new release. I can take a look and get moving for y'all.

**Comment by stephencweiss** [comment]
@duggiefresh - any movement here?

**Comment by duggiefresh** [comment]
@stephencweiss Hello and apologies for the wait! I just published a v0.7.2. Please let me know if that resolves your issue. Thank you 🙌

**Comment by robbytx** [comment]
This issue can probably be closed now.
