### ISSUE TITLE
Push latest updates.

### ISSUE THREAD

**Issue by The-Don-Himself** [DockYard/ember-service-worker-index#3]
First, thanks for the awesome plugin, I referenced it in a Ember post where the was a discussion on boot times.
https://discuss.emberjs.com/t/for-feedback-splash-screen-for-index-html-with-gist/13053

Anyway, i'm opening this issue because The latest improvements come with a significant advantage of excluding some matching urls. Kindly push them when you have time so that people can benefit.

**Comment by topaxi** [comment]
Anything holding up a new release? I'd be happy to help out.

**Comment by ghost** [comment]
Done
